An attempt to fix sphinx build action
The following flags are added to the command:

    '-w', '/tmp/sphinx-log'

This is causing the following issue:

    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/sphinx-log'

This may be related to this issue:

    https://github.com/ammaraskar/sphinx-action/issues/5

Attempted to fix this by forcing the upgrade of sphinx and docutils.
Possibly the issue comes from the way older version would behave when
passed -w. TBD.